/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Robotics_2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/viewing2/Robotics_2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.020"]}
        position={[-0.364, 3.042, -0.199]}
        rotation={[0, -0.009, -0.003]}
        scale={[1.21, 1, 2.331]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0.796, 4.551, 0]}
        scale={[0.095, 0.154, 3.735]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.002"]}
        position={[0.788, 3.863, -0.199]}
        rotation={[0.283, 0, 0]}
        scale={[0.095, 0.142, 2.425]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.003"]}
        position={[0.788, 3.863, -0.199]}
        rotation={[-0.293, 0, 0]}
        scale={[0.095, 0.142, 2.425]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.005"]}
        position={[0.788, 3.863, -3.074]}
        rotation={[0.844, 0, 0]}
        scale={[0.101, 0.054, 1.055]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.004"]}
        position={[0.788, 3.863, 2.951]}
        rotation={[2.435, 0, 0]}
        scale={[0.101, 0.054, 1.055]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.009"]}
        position={[-1.501, 3.863, -0.199]}
        rotation={[0.283, 0, 0]}
        scale={[0.095, 0.142, 2.425]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials["Material.008"]}
        position={[-1.508, 3.863, -0.199]}
        rotation={[-0.293, 0, 0]}
        scale={[0.095, 0.142, 2.425]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.007"]}
        position={[-1.53, 4.551, 0]}
        scale={[0.095, 0.154, 3.735]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Material.019"]}
        position={[-1.529, 3.863, -3.074]}
        rotation={[0.844, 0, 0]}
        scale={[0.101, 0.054, 1.055]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials["Material.010"]}
        position={[-1.51, 3.863, 2.951]}
        rotation={[2.435, 0, 0]}
        scale={[0.101, 0.054, 1.055]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.014"]}
        position={[0.802, 3.19, -2.524]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.015"]}
        position={[0.802, 4.541, -3.793]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.012"]}
        position={[0.802, 4.541, 3.697]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.013"]}
        position={[0.802, 3.169, 2.202]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.016"]}
        position={[-1.53, 4.541, -3.742]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials["Material.017"]}
        position={[-1.53, 3.187, -2.511]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.018"]}
        position={[-1.53, 3.187, 2.194]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.034"]}
        position={[0.839, 4.119, 4.232]}
        rotation={[-0.865, 0, 0]}
        scale={[0.138, 0.542, 0.135]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.011"]}
        position={[-1.542, 4.541, 3.697]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.035"]}
        position={[-1.551, 4.119, 4.232]}
        rotation={[-0.865, 0, 0]}
        scale={[0.138, 0.542, 0.135]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.Material}
        position={[0.87, 4.512, 3.785]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Sphere001.geometry}
        material={materials["Material.026"]}
        position={[-1.596, 4.512, 3.785]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials["Material.030"]}
        position={[0.842, 3.012, 5.133]}
        rotation={[-1.167, 0, 0]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.042"]}
        position={[-1.553, 3.012, 5.133]}
        rotation={[-1.167, 0, 0]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials["Material.029"]}
        position={[0.842, 3.301, 3.434]}
        rotation={[-1.575, 0, 0]}
        scale={[0.061, 1.022, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials["Material.041"]}
        position={[-1.552, 3.301, 3.434]}
        rotation={[-1.575, 0, 0]}
        scale={[0.061, 1.022, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material.043"]}
        position={[0.802, 2.811, 5.785]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials["Material.045"]}
        position={[-1.505, 2.811, 5.785]}
        rotation={[1.57, -0.015, 1.601]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials["Material.044"]}
        position={[1.445, 2.782, 5.74]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[1.276, 0.476, 1.231]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.046"]}
        position={[-2.156, 2.782, 5.74]}
        rotation={[1.57, -0.023, 1.601]}
        scale={[1.276, 0.476, 1.231]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.021"]}
        position={[-0.372, 3.893, 2.962]}
        rotation={[2.435, 0, 0]}
        scale={[1.044, 1.222, 1.23]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials["Material.036"]}
        position={[0.798, 4.119, -4.224]}
        rotation={[0.858, 0, 0]}
        scale={[0.138, 0.542, 0.135]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials["Material.037"]}
        position={[-1.522, 4.119, -4.224]}
        rotation={[0.858, 0, 0]}
        scale={[0.138, 0.542, 0.135]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials["Material.054"]}
        position={[-1.553, 3.012, -5.078]}
        rotation={[-1.956, 0, 0]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials["Material.052"]}
        position={[0.783, 3.012, -5.078]}
        rotation={[-1.963, 0, 0]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials["Material.051"]}
        position={[0.794, 3.301, -3.46]}
        rotation={[-1.575, 0, 0]}
        scale={[0.061, 1.022, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials["Material.053"]}
        position={[-1.53, 3.301, -3.46]}
        rotation={[-1.575, 0, 0]}
        scale={[0.061, 1.022, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials["Material.055"]}
        position={[0.802, 2.811, -5.84]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials["Material.056"]}
        position={[-1.505, 2.811, -5.895]}
        rotation={[1.57, -0.015, 1.601]}
        scale={[0.263, 0.137, 0.275]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials["Material.058"]}
        position={[1.445, 2.782, -5.827]}
        rotation={[-1.57, -0.004, -1.541]}
        scale={[1.276, 0.476, 1.231]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={materials["Material.057"]}
        position={[-2.156, 2.782, -5.929]}
        rotation={[1.57, -0.023, 1.601]}
        scale={[1.276, 0.476, 1.231]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.022"]}
        position={[-0.372, 4.67, 2.684]}
        rotation={[3.104, 0, 0]}
        scale={[1.044, 1.222, 1.23]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.023"]}
        position={[-0.372, 4.67, -2.669]}
        rotation={[-3.126, 0, 0]}
        scale={[1.044, 1.222, 1.23]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={materials["Material.047"]}
        position={[0.282, 2.803, 5.755]}
        rotation={[0, 0, -1.578]}
        scale={[0.172, 0.363, 0.206]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={materials["Material.006"]}
        position={[-0.359, 4.573, 3.819]}
        rotation={[0, 0, -1.578]}
        scale={[0.172, 1.035, 0.206]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={materials["Material.050"]}
        position={[-1.011, 2.803, 5.755]}
        rotation={[0, 0, -1.578]}
        scale={[0.172, 0.363, 0.206]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Material.048"]}
        position={[-0.059, 2.976, 5.736]}
        scale={[0.07, 0.295, 0.127]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.049"]}
        position={[-0.659, 2.976, 5.736]}
        scale={[0.07, 0.295, 0.127]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={materials["Material.032"]}
        position={[0.146, 3.529, 5.133]}
        rotation={[-1.184, -0.118, -0.281]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={materials["Material.039"]}
        position={[-0.893, 3.529, 5.133]}
        rotation={[-1.189, 0.135, 0.323]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={materials["Material.031"]}
        position={[0.551, 3.851, 3.765]}
        rotation={[-1.573, -0.118, -0.281]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={materials["Material.038"]}
        position={[-1.304, 3.851, 3.765]}
        rotation={[-1.515, -0.104, 0.236]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["Material.033"]}
        position={[-0.043, 3.256, 5.723]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials["Material.040"]}
        position={[-0.662, 3.256, 5.723]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials["Material.024"]}
        position={[0.762, 3.876, 3.05]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.111, -0.09, -0.119]}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials["Material.025"]}
        position={[-1.456, 3.876, 3.05]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.111, -0.09, -0.119]}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials["Material.027"]}
        position={[-1.596, 4.512, -3.785]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Sphere007.geometry}
        material={materials["Material.028"]}
        position={[0.861, 4.512, -3.785]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={materials["Material.059"]}
        position={[0.308, 2.803, -5.818]}
        rotation={[0, 0, -1.578]}
        scale={[0.172, 0.363, 0.206]}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={materials["Material.060"]}
        position={[-1.008, 2.803, -5.818]}
        rotation={[0, 0, -1.578]}
        scale={[0.172, 0.363, 0.206]}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={materials["Material.061"]}
        position={[-1.295, 3.851, -3.851]}
        rotation={[-1.573, -0.118, -0.281]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={materials["Material.062"]}
        position={[0.601, 3.851, -3.87]}
        rotation={[-1.515, -0.104, 0.236]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={materials["Material.063"]}
        position={[-0.885, 3.579, -5.203]}
        rotation={[-2.042, -0.118, -0.281]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={materials["Material.064"]}
        position={[0.184, 3.579, -5.218]}
        rotation={[-1.878, -0.381, 0.357]}
        scale={[0.061, 0.766, 0.05]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.065"]}
        position={[-0.059, 2.989, -5.844]}
        scale={[0.07, 0.295, 0.127]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Material.066"]}
        position={[-0.657, 2.989, -5.844]}
        scale={[0.07, 0.295, 0.127]}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={materials["Material.067"]}
        position={[-0.052, 3.205, -5.842]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={materials["Material.068"]}
        position={[-0.648, 3.205, -5.842]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["Material.069"]}
        position={[-0.359, 5.061, -2.668]}
        scale={[0.984, 0.381, 1.154]}
      />
      <mesh
        geometry={nodes.Cylinder041.geometry}
        material={materials["Material.070"]}
        position={[-0.371, 4.605, -0.748]}
        rotation={[-1.571, 0.005, -1.559]}
        scale={[0.061, 1.097, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={materials["Material.071"]}
        position={[-0.371, 4.605, 0.351]}
        rotation={[-1.571, 0.005, -1.559]}
        scale={[0.061, 1.097, 0.05]}
      />
      <mesh
        geometry={nodes.Sphere010.geometry}
        material={materials["Material.072"]}
        position={[0.87, 4.512, -0.778]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.107, -0.088, -0.081]}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={materials["Material.073"]}
        position={[0.87, 4.512, 0.341]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.107, -0.088, -0.081]}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={materials["Material.074"]}
        position={[-1.579, 4.512, 0.341]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.107, -0.088, -0.081]}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={materials["Material.075"]}
        position={[-1.628, 4.512, -0.778]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.107, -0.088, -0.081]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["Material.077"]}
        position={[-0.301, 4.851, 2.578]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.12, -1.093]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["Material.079"]}
        position={[-0.656, 5.108, 2.122]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.586, -0.173, -0.617]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.078"]}
        position={[0.467, 5.026, 3.142]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.191, -0.094, -0.426]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["Material.080"]}
        position={[-1.009, 5.141, 3.239]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.191, -0.122, -0.426]}
      />
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={materials["Material.076"]}
        position={[-0.728, 4.555, 1.105]}
        rotation={[1.577, 1.562, 1.576]}
        scale={[0.061, 1.544, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder044.geometry}
        material={materials["Material.081"]}
        position={[-0.733, 5.513, 1.377]}
        rotation={[1.111, 1.562, 1.576]}
        scale={[0.043, 0.565, 0.05]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[-0.246, 5.247, 2.501]}
        scale={[0.089, 0.035, 0.078]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[-0.246, 5.247, 2.312]}
        scale={[0.089, 0.035, 0.078]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-0.246, 5.247, 2.113]}
        scale={[0.089, 0.035, 0.078]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-0.246, 5.247, 1.915]}
        scale={[0.089, 0.035, 0.078]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[-1.107, 5.247, 2.501]}
        scale={[0.089, 0.035, 0.078]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[-1.107, 5.247, 1.699]}
        scale={[0.089, 0.035, 0.078]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[-1.107, 5.247, 2.33]}
        scale={[0.125, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[-1.107, 5.247, 2.188]}
        scale={[0.125, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[-1.107, 5.247, 2.062]}
        scale={[0.125, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[-1.107, 5.247, 1.919]}
        scale={[0.125, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[-0.49, 5.247, 1.919]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        position={[-0.684, 5.247, 1.919]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={nodes.Cube031.material}
        position={[-0.898, 5.247, 1.919]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={nodes.Cube032.material}
        position={[-0.898, 5.247, 2.197]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={nodes.Cube033.material}
        position={[-0.898, 5.247, 2.472]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={nodes.Cube034.material}
        position={[-0.695, 5.247, 2.472]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={nodes.Cube035.material}
        position={[-0.506, 5.247, 2.472]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={nodes.Cube036.material}
        position={[-0.506, 5.247, 2.181]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={nodes.Cube037.material}
        position={[-0.189, 5.247, 1.736]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.061, 0.035, 0.011]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={nodes.Cube038.material}
        position={[-0.306, 5.247, 1.736]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.061, 0.035, 0.011]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={nodes.Cube039.material}
        position={[-0.427, 5.247, 1.736]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.061, 0.035, 0.011]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={nodes.Cube040.material}
        position={[-0.427, 5.247, 1.601]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.019, 0.035, 0.011]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        position={[-0.313, 5.247, 1.601]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.019, 0.035, 0.011]}
      />
      <mesh
        geometry={nodes.Cube042.geometry}
        material={nodes.Cube042.material}
        position={[-0.189, 5.247, 1.601]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.019, 0.035, 0.011]}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={materials["Material.082"]}
        position={[-0.687, 5.236, 1.67]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.152, -0.147, -0.173]}
      />
      <mesh
        geometry={nodes.Cube043.geometry}
        material={nodes.Cube043.material}
        position={[-0.718, 6.095, 1.128]}
        rotation={[-0.295, 0, 0]}
        scale={[0.156, 0.035, 0.152]}
      />
      <mesh
        geometry={nodes.Cylinder045.geometry}
        material={nodes.Cylinder045.material}
        position={[-1.017, 5.209, 3.221]}
        rotation={[1.585, 0, 0]}
        scale={[0.139, 0.326, 0.134]}
      />
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={materials["Material.085"]}
        position={[0.479, 5.015, 3.879]}
        rotation={[-1.55, -0.011, -0.027]}
        scale={[0.044, 0.301, 0.036]}
      />
      <mesh
        geometry={nodes.Sphere015.geometry}
        material={materials["Material.086"]}
        position={[0.473, 5.009, 4.138]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.054, -0.057, -0.08]}
      />
      <mesh
        geometry={nodes.Cube044.geometry}
        material={materials["Material.087"]}
        position={[0.478, 4.611, 4.165]}
        rotation={[1.539, 0, 0]}
        scale={[0.051, 0.046, 0.427]}
      />
      <mesh
        geometry={nodes.Cube045.geometry}
        material={nodes.Cube045.material}
        position={[0.55, 5.125, 3.474]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube046.geometry}
        material={nodes.Cube046.material}
        position={[0.55, 5.125, 3.401]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.028, 0.035, 0.026]}
      />
      <mesh
        geometry={nodes.Cube047.geometry}
        material={nodes.Cube047.material}
        position={[0.55, 5.125, 3.276]}
        rotation={[-Math.PI, 1.554, -Math.PI]}
        scale={[0.057, 0.035, 0.017]}
      />
      <mesh
        geometry={nodes.Cube048.geometry}
        material={materials["Material.095"]}
        position={[-0.301, 3.34, -0.309]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.12, -1.093]}
      />
    </group>
  );
}

useGLTF.preload("/Robotics_2.glb");
